services:
  - type: web
    name: medical-ocr-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: AZURE_DOCUMENT_INTELLIGENCE_API_KEY
        sync: false
      - key: AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT
        sync: false
      - key: AZURE_DOCUMENT_INTELLIGENCE_MODEL_ID
        value: prebuilt-layout
        sync: false
    autoDeploy: true
    plan: free
